services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ddc_user
      POSTGRES_PASSWORD: ddc_pass
      POSTGRES_DB: ddc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://ddc_user:ddc_pass@db:5432/ddc_db
      SECRET_KEY: clave_secreta_jwt_cambiar_en_produccion
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      INACTIVITY_TIMEOUT_MINUTES: 30
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/package.json:/app/package.json
      - node_modules:/app/node_modules

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/ddc_db
      SONAR_JDBC_USERNAME: ddc_user
      SONAR_JDBC_PASSWORD: ddc_pass
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    depends_on:
      - db
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  postgres_data:
  node_modules:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
