from app.models.usuario import Usuario
from app.models.refresh_token import RefreshToken
from app.models.cliente import Cliente
from app.models.persona_natural import PersonaNatural
from app.models.persona_juridica import PersonaJuridica
from app.models.representante_legal import RepresentanteLegal
from app.models.beneficiario_final import BeneficiarioFinal
from app.models.documento import Documento
from app.models.perfil_financiero import PerfilFinanciero
from app.models.perfil_transaccional import PerfilTransaccional
from app.models.version_matriz_riesgo import VersionMatrizRiesgo
from app.models.factor_riesgo import FactorRiesgo
from app.models.clasificacion_riesgo import ClasificacionRiesgo
from app.models.observacion import Observacion
from app.models.auditoria import Auditoria
from app.models.auditoria_admin import AuditoriaAdmin
